name: bio
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^5.2.5
  firebase_auth: ^4.10.0
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  get: 4.6.5
  google_fonts: ^5.1.0
  image_picker: ^0.8.6+1
  intl: ^0.18.1
  need_resume: null
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/exam.png
    - assets/images/logo.png
    - assets/images/q1.png
    - assets/images/q2.png
    - assets/images/q3.png
    - assets/images/q4.png
    - assets/images/q5.png
    - assets/images/q6.png
    - assets/images/q7.png
    - assets/images/logo_icon.png
