name: bio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^5.1.0
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  laravel_exception: ^0.0.4
  location: ^4.4.0
  lottie: ^2.2.0
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  need_resume: 
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/exam.png
    
